In [1]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
words = open('names.txt', 'r').read().splitlines()

In [3]:
words[:10]

['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn']

In [8]:
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i, s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s, i in stoi.items()}
print(itos)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}


In [11]:
block_size = 3
X, Y = [], []

for w in words[:5]:
    print(w)
    context = [0] * block_size
    for ch in w + '.':
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)
        print(''.join(itos[i] for i in context), '--->', itos[ix])
        context = context[1:] + [ix]

X = torch.tensor(X)
Y = torch.tensor(Y)

emma
... ---> e
..e ---> m
.em ---> m
emm ---> a
mma ---> .
olivia
... ---> o
..o ---> l
.ol ---> i
oli ---> v
liv ---> i
ivi ---> a
via ---> .
ava
... ---> a
..a ---> v
.av ---> a
ava ---> .
isabella
... ---> i
..i ---> s
.is ---> a
isa ---> b
sab ---> e
abe ---> l
bel ---> l
ell ---> a
lla ---> .
sophia
... ---> s
..s ---> o
.so ---> p
sop ---> h
oph ---> i
phi ---> a
hia ---> .


In [12]:
C = torch.randn((27, 2))

In [13]:
C

tensor([[-0.8714, -0.8808],
        [-1.6864,  0.7938],
        [ 0.5207, -1.3470],
        [ 1.5123,  0.5831],
        [ 0.7350, -2.2573],
        [-0.6039,  0.8553],
        [ 0.1809, -0.9646],
        [ 0.2612, -1.3283],
        [ 0.4430,  0.1265],
        [-0.9627,  1.1447],
        [ 1.6481,  0.6616],
        [-0.5735,  0.8898],
        [-0.0848, -0.4682],
        [-0.4807,  0.2980],
        [-1.7398,  0.6151],
        [-1.5134, -0.2002],
        [-0.6735,  1.7934],
        [ 1.8017,  0.9470],
        [ 0.9317, -1.6379],
        [ 1.0685, -1.2354],
        [-0.1688,  2.1558],
        [ 0.4278, -0.0863],
        [ 1.0488, -0.3056],
        [ 0.2550, -0.6274],
        [ 0.0793, -0.3126],
        [-1.0433, -0.8786],
        [ 0.3705,  2.8794]])

In [14]:
 X.shape

torch.Size([32, 3])

In [15]:
X

tensor([[ 0,  0,  0],
        [ 0,  0,  5],
        [ 0,  5, 13],
        [ 5, 13, 13],
        [13, 13,  1],
        [ 0,  0,  0],
        [ 0,  0, 15],
        [ 0, 15, 12],
        [15, 12,  9],
        [12,  9, 22],
        [ 9, 22,  9],
        [22,  9,  1],
        [ 0,  0,  0],
        [ 0,  0,  1],
        [ 0,  1, 22],
        [ 1, 22,  1],
        [ 0,  0,  0],
        [ 0,  0,  9],
        [ 0,  9, 19],
        [ 9, 19,  1],
        [19,  1,  2],
        [ 1,  2,  5],
        [ 2,  5, 12],
        [ 5, 12, 12],
        [12, 12,  1],
        [ 0,  0,  0],
        [ 0,  0, 19],
        [ 0, 19, 15],
        [19, 15, 16],
        [15, 16,  8],
        [16,  8,  9],
        [ 8,  9,  1]])

In [16]:
Y

tensor([ 5, 13, 13,  1,  0, 15, 12,  9, 22,  9,  1,  0,  1, 22,  1,  0,  9, 19,
         1,  2,  5, 12, 12,  1,  0, 19, 15, 16,  8,  9,  1,  0])

In [18]:
emb = C[X]
emb.shape

torch.Size([32, 3, 2])

In [19]:
W1 = torch.randn((6, 100))
b1 = torch.randn(100)

In [20]:
torch.cat(torch.unbind(emb, 1), 1).shape

torch.Size([32, 6])

In [24]:
h = torch.tanh(emb.view(-1, 6) @ W1 + b1)

In [25]:
h

tensor([[-0.1979, -0.9992,  0.2004,  ...,  0.9118,  0.1297,  0.9775],
        [ 0.9263, -0.9052,  0.1224,  ..., -0.1202, -0.8769,  0.9990],
        [ 0.9969,  0.8137, -0.7398,  ...,  0.9708, -0.9974,  0.9945],
        ...,
        [ 0.9996,  0.9013, -0.4791,  ...,  0.9997, -0.9837,  0.5100],
        [ 0.9983,  0.7162,  0.9944,  ...,  0.8775,  0.9975,  0.9501],
        [ 0.9999,  0.9997, -0.3667,  ...,  0.7313, -0.0797,  0.9993]])

In [26]:
h.shape

torch.Size([32, 100])

In [27]:
W2 = torch.randn(100, 27)
b2 = torch.randn(27)

In [28]:
logits = h @ W2 + b2

In [29]:
logits.shape

torch.Size([32, 27])

In [30]:
counts = logits.exp()

In [31]:
counts

tensor([[3.2975e-09, 1.5281e-03, 2.6602e+04, 5.6659e+00, 1.4916e-02, 2.0498e+04,
         6.9647e-06, 1.1964e+03, 1.5144e+04, 2.0475e-01, 1.9299e-02, 4.8059e+03,
         1.2935e-05, 7.5265e+02, 7.3802e+05, 5.8820e+04, 1.1789e-03, 1.7315e+02,
         1.4353e+01, 6.1293e+03, 2.0253e-01, 1.2241e+07, 1.1538e+07, 1.7388e+02,
         3.7181e+01, 1.9965e+03, 2.0471e+06],
        [2.1821e-07, 7.9535e-02, 1.0888e+05, 5.5116e+01, 3.3690e-01, 7.6772e+03,
         2.4022e-03, 4.8546e+03, 2.3046e+05, 3.6337e-04, 2.0018e-04, 1.4802e+00,
         1.1222e-05, 4.3368e-03, 9.9979e+00, 2.9672e+04, 6.1273e-04, 1.2243e-02,
         6.3929e+02, 1.3272e+03, 1.1915e+01, 3.6667e+03, 7.7679e+02, 9.2187e+04,
         1.0233e-01, 2.7195e+04, 5.6782e+05],
        [7.4014e-03, 2.2881e+00, 2.0536e+05, 1.0765e-02, 3.8864e+00, 1.2053e+03,
         1.3111e-04, 7.2977e+02, 1.0729e-03, 9.1574e-05, 2.4261e-08, 2.1653e-01,
         2.5982e-01, 4.6931e-03, 4.7678e-01, 1.4461e+02, 1.0988e-05, 7.5283e-01,
         1.6632e+

In [32]:
probs = counts / counts.sum(1, keepdims=True)

In [33]:
probs.shape

torch.Size([32, 27])

In [34]:
probs

tensor([[1.2350e-16, 5.7231e-11, 9.9633e-04, 2.1221e-07, 5.5866e-10, 7.6771e-04,
         2.6085e-13, 4.4809e-05, 5.6718e-04, 7.6686e-09, 7.2280e-10, 1.8000e-04,
         4.8447e-13, 2.8189e-05, 2.7641e-02, 2.2030e-03, 4.4153e-11, 6.4852e-06,
         5.3757e-07, 2.2956e-04, 7.5855e-09, 4.5845e-01, 4.3213e-01, 6.5122e-06,
         1.3925e-06, 7.4775e-05, 7.6670e-02],
        [2.0294e-13, 7.3969e-08, 1.0127e-01, 5.1259e-05, 3.1333e-07, 7.1400e-03,
         2.2341e-09, 4.5149e-03, 2.1433e-01, 3.3794e-10, 1.8617e-10, 1.3766e-06,
         1.0437e-11, 4.0334e-09, 9.2983e-06, 2.7596e-02, 5.6986e-10, 1.1387e-08,
         5.9456e-04, 1.2343e-03, 1.1081e-05, 3.4101e-03, 7.2244e-04, 8.5736e-02,
         9.5169e-08, 2.5292e-02, 5.2809e-01],
        [1.4854e-10, 4.5921e-08, 4.1215e-03, 2.1604e-10, 7.7998e-08, 2.4190e-05,
         2.6312e-12, 1.4646e-05, 2.1532e-11, 1.8379e-12, 4.8692e-16, 4.3457e-09,
         5.2144e-09, 9.4188e-11, 9.5688e-09, 2.9023e-06, 2.2052e-13, 1.5109e-08,
         3.3380e-

In [37]:
probs[torch.arange(32), Y]

tensor([7.6771e-04, 4.0334e-09, 9.4188e-11, 3.1092e-08, 5.3194e-06, 2.2030e-03,
        9.2151e-11, 2.0761e-11, 6.0248e-06, 3.1508e-11, 4.9802e-10, 6.4245e-02,
        5.7231e-11, 4.5050e-03, 1.0616e-06, 2.5700e-10, 7.6686e-09, 2.2198e-04,
        1.3662e-06, 3.0775e-09, 1.4693e-10, 3.7669e-14, 3.6509e-04, 2.3721e-12,
        6.8615e-10, 2.2956e-04, 9.1910e-02, 1.3945e-08, 1.0916e-07, 1.1249e-11,
        1.0613e-06, 2.8599e-05])

In [35]:
torch.arange(32)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [38]:
Y.shape

torch.Size([32])